# Generated by Django 5.2.6 on 2026-02-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogym1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TRAINER', 'Trainer'), ('MEMBER', 'Member')], default='MEMBER', max_length=10),
        ),
    ]
