# Generated by Django 5.2.6 on 2026-05-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogym1', '0006_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
