# Generated by Django 5.2.6 on 2026-05-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogym1', '0007_alter_adminuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='access_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
