# Generated by Django 5.2.6 on 2026-05-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogym1', '0008_adminprofile_access_expires_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='grace_period_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='plan_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
    ]
